application: google.com:angulardart
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "10m"

handlers:
- url: /favicon\.ico
  static_files: app/img/favicon.ico
  upload: app/img/favicon.ico

- url: /demo/.*
  static_dir: app/demo

- url: /demo/?
  static_files: app/demo/index.html
  upload: app/demo/index.html

- url: /tutorial/.*
  static_dir: app/tutorial

- url: /tutorial/?
  static_files: app/tutorial/index.html
  upload: app/tutorial/index.html

- url: /
  static_files: app/index.html
  upload: app/index\.html
  mime_type: text/html; charset=utf-8

- url: (/.*\.css)
  static_files: app\1
  upload: app/.*\.css
  mime_type: text/css; charset=utf-8

- url: (/.*\.html)
  static_files: app\1
  upload: app/.*\.html
  mime_type: text/html; charset=utf-8

- url: (/.*\.json)
  static_files: app\1
  upload: app/.*\.json
  mime_type: application/json; charset=utf-8

- url: (/.*\.js)
  static_files: app\1
  upload: app/.*\.js
  mime_type: text/javascript; charset=utf-8

- url: (/.*\.png)
  static_files: app\1
  upload: app/.*\.png
  mime_type: image/png

- url: /tutorial/
  static_files: app/tutorial/index\.html
  upload: app/tutorial/index\.html
  mime_type: text/html; charset=utf-8



